"""add unit_embeddings

Revision ID: d72569034d1a
Revises: 49e4dfb67e38
Create Date: 2026-09-29 23:48:28.375849+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72569034d1a'
down_revision: Union[str, None] = '49e4dfb67e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('unit_kind', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('index_status', sa.String(length=32), nullable=False),
    sa.Column('vector_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_kind', 'unit_id', 'embedding_model', name='uq_unit_embeddings_kind_unit_model')
    )
    op.create_index(op.f('ix_unit_embeddings_kb_id'), 'unit_embeddings', ['kb_id'], unique=False)
    op.create_index('ix_unit_embeddings_kb_kind_model', 'unit_embeddings', ['kb_id', 'unit_kind', 'embedding_model'], unique=False)
    op.create_index(op.f('ix_unit_embeddings_owner_wallet_address'), 'unit_embeddings', ['owner_wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_embeddings_owner_wallet_address'), table_name='unit_embeddings')
    op.drop_index('ix_unit_embeddings_kb_kind_model', table_name='unit_embeddings')
    op.drop_index(op.f('ix_unit_embeddings_kb_id'), table_name='unit_embeddings')
    op.drop_table('unit_embeddings')
    # ### end Alembic commands ###
