"""initial schema

Revision ID: 49e4dfb67e38
Revises: 
Create Date: 2026-09-29 07:10:27.465373+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e4dfb67e38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_auth_challenges_wallet_address'), 'auth_challenges', ['wallet_address'], unique=False)
    op.create_table('memories_short_term',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ttl_or_expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_short_term_owner_wallet_address'), 'memories_short_term', ['owner_wallet_address'], unique=False)
    op.create_index(op.f('ix_memories_short_term_session_id'), 'memories_short_term', ['session_id'], unique=False)
    op.create_table('passport_login_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('authorization_code', sa.String(length=2048), nullable=True),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_passport_login_sessions_subject_id'), 'passport_login_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_passport_login_sessions_wallet_address'), 'passport_login_sessions', ['wallet_address'], unique=False)
    op.create_table('upload_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('warehouse_target_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_records_owner_wallet_address'), 'upload_records', ['owner_wallet_address'], unique=False)
    op.create_table('wallet_users',
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('wallet_address')
    )
    op.create_table('warehouse_access_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('credential_kind', sa.String(length=16), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('encrypted_key_secret', sa.Text(), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_wallet_address', 'credential_kind', 'key_id', 'root_path', name='uq_warehouse_access_credential_owner_kind_key_root')
    )
    op.create_index(op.f('ix_warehouse_access_credentials_owner_wallet_address'), 'warehouse_access_credentials', ['owner_wallet_address'], unique=False)
    op.create_table('worker_status',
    sa.Column('worker_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('worker_name')
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieval_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_wallet_address'], ['wallet_users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_owner_wallet_address'), 'knowledge_bases', ['owner_wallet_address'], unique=False)
    op.create_table('passport_subjects',
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_address'], ['wallet_users.wallet_address'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_passport_subjects_wallet_address'), 'passport_subjects', ['wallet_address'], unique=False)
    op.create_table('service_principals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('identity_type', sa.String(length=32), nullable=False),
    sa.Column('credential_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('public_key_jwk', sa.JSON(), nullable=False),
    sa.Column('principal_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_wallet_address'], ['wallet_users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_wallet_address', 'service_id', name='uq_service_principals_owner_service_id')
    )
    op.create_index('ix_service_principals_owner_status', 'service_principals', ['owner_wallet_address', 'principal_status'], unique=False)
    op.create_index(op.f('ix_service_principals_owner_wallet_address'), 'service_principals', ['owner_wallet_address'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('service_principal_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('warehouse_run_path', sa.String(length=1024), nullable=False),
    sa.Column('input_manifest_json', sa.JSON(), nullable=False),
    sa.Column('context_manifest_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('manifest_sync_status', sa.String(length=32), nullable=False),
    sa.Column('manifest_synced_at', sa.DateTime(), nullable=True),
    sa.Column('manifest_sync_error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_wallet_address'], ['wallet_users.wallet_address'], ),
    sa.ForeignKeyConstraint(['service_principal_id'], ['service_principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_principal_id', 'external_id', name='uq_agent_runs_principal_external_id')
    )
    op.create_index('ix_agent_runs_owner_created_at', 'agent_runs', ['owner_wallet_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_owner_wallet_address'), 'agent_runs', ['owner_wallet_address'], unique=False)
    op.create_index('ix_agent_runs_principal_created_at', 'agent_runs', ['service_principal_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_service_principal_id'), 'agent_runs', ['service_principal_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_etag_or_mtime', sa.String(length=128), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'source_path', name='uq_kb_document_source_path')
    )
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.create_index(op.f('ix_documents_owner_wallet_address'), 'documents', ['owner_wallet_address'], unique=False)
    op.create_table('import_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_paths', sa.JSON(), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('last_stage', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_tasks_kb_id'), 'import_tasks', ['kb_id'], unique=False)
    op.create_index('ix_import_tasks_owner_status_created_at', 'import_tasks', ['owner_wallet_address', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_import_tasks_owner_wallet_address'), 'import_tasks', ['owner_wallet_address'], unique=False)
    op.create_index('ix_import_tasks_status_created_at', 'import_tasks', ['status', 'created_at'], unique=False)
    op.create_table('kb_releases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('release_note', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('supersedes_release_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['supersedes_release_id'], ['kb_releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'version', name='uq_kb_releases_kb_version')
    )
    op.create_index(op.f('ix_kb_releases_kb_id'), 'kb_releases', ['kb_id'], unique=False)
    op.create_index('ix_kb_releases_kb_status_published_at', 'kb_releases', ['kb_id', 'status', 'published_at'], unique=False)
    op.create_index(op.f('ix_kb_releases_supersedes_release_id'), 'kb_releases', ['supersedes_release_id'], unique=False)
    op.create_table('knowledge_item_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('structured_payload_json', sa.JSON(), nullable=False),
    sa.Column('item_contract_version', sa.String(length=32), nullable=False),
    sa.Column('origin_type', sa.String(length=32), nullable=False),
    sa.Column('origin_confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_from_job_id', sa.String(length=128), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_item_candidates_kb_id'), 'knowledge_item_candidates', ['kb_id'], unique=False)
    op.create_index('ix_knowledge_item_candidates_kb_review_status', 'knowledge_item_candidates', ['kb_id', 'review_status'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('origin_type', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('is_hotfix', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_current_revision_id'), 'knowledge_items', ['current_revision_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_kb_id'), 'knowledge_items', ['kb_id'], unique=False)
    op.create_index('ix_knowledge_items_kb_lifecycle_status', 'knowledge_items', ['kb_id', 'lifecycle_status'], unique=False)
    op.create_table('memories_long_term',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_long_term_kb_id'), 'memories_long_term', ['kb_id'], unique=False)
    op.create_index(op.f('ix_memories_long_term_owner_wallet_address'), 'memories_long_term', ['owner_wallet_address'], unique=False)
    op.create_table('memory_ingestion_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('query_preview', sa.Text(), nullable=False),
    sa.Column('answer_preview', sa.Text(), nullable=False),
    sa.Column('source_refs_json', sa.JSON(), nullable=False),
    sa.Column('short_term_created', sa.Integer(), nullable=False),
    sa.Column('long_term_created', sa.Integer(), nullable=False),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_ingestion_events_kb_id'), 'memory_ingestion_events', ['kb_id'], unique=False)
    op.create_index(op.f('ix_memory_ingestion_events_owner_wallet_address'), 'memory_ingestion_events', ['owner_wallet_address'], unique=False)
    op.create_index(op.f('ix_memory_ingestion_events_session_id'), 'memory_ingestion_events', ['session_id'], unique=False)
    op.create_table('source_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_imported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'source_path', name='uq_kb_source_path')
    )
    op.create_index(op.f('ix_source_bindings_credential_id'), 'source_bindings', ['credential_id'], unique=False)
    op.create_index(op.f('ix_source_bindings_kb_id'), 'source_bindings', ['kb_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('missing_policy', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'source_path', name='uq_sources_kb_source_path')
    )
    op.create_index(op.f('ix_sources_kb_id'), 'sources', ['kb_id'], unique=False)
    op.create_index('ix_sources_kb_sync_status', 'sources', ['kb_id', 'sync_status'], unique=False)
    op.create_table('agent_run_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_key', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('warehouse_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('generated_by_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'artifact_key', name='uq_agent_run_artifacts_run_key')
    )
    op.create_index(op.f('ix_agent_run_artifacts_run_id'), 'agent_run_artifacts', ['run_id'], unique=False)
    op.create_table('agent_run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_agent_run_events_run_sequence')
    )
    op.create_index(op.f('ix_agent_run_events_run_id'), 'agent_run_events', ['run_id'], unique=False)
    op.create_table('agent_run_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('input_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('warehouse_path', sa.String(length=1024), nullable=False),
    sa.Column('version_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'input_key', name='uq_agent_run_inputs_run_key')
    )
    op.create_index(op.f('ix_agent_run_inputs_run_id'), 'agent_run_inputs', ['run_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_agent_run_steps_run_sequence')
    )
    op.create_index(op.f('ix_agent_run_steps_run_id'), 'agent_run_steps', ['run_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_kb_id'), 'chunks', ['kb_id'], unique=False)
    op.create_index(op.f('ix_chunks_owner_wallet_address'), 'chunks', ['owner_wallet_address'], unique=False)
    op.create_table('import_task_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['import_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_task_items_task_id'), 'import_task_items', ['task_id'], unique=False)
    op.create_table('knowledge_item_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('structured_payload_json', sa.JSON(), nullable=False),
    sa.Column('item_contract_version', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('visibility_status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=False),
    sa.Column('provenance_type', sa.String(length=32), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('applicability_scope_json', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_workspace_head', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_item_id', 'revision_no', name='uq_knowledge_item_revisions_item_revision_no')
    )
    op.create_index('ix_knowledge_item_revisions_item_review_visibility', 'knowledge_item_revisions', ['knowledge_item_id', 'review_status', 'visibility_status'], unique=False)
    op.create_index(op.f('ix_knowledge_item_revisions_knowledge_item_id'), 'knowledge_item_revisions', ['knowledge_item_id'], unique=False)
    op.create_table('service_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('service_principal_id', sa.Integer(), nullable=False),
    sa.Column('grant_status', sa.String(length=32), nullable=False),
    sa.Column('release_selection_mode', sa.String(length=32), nullable=False),
    sa.Column('pinned_release_id', sa.Integer(), nullable=True),
    sa.Column('default_result_mode', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['owner_wallet_address'], ['wallet_users.wallet_address'], ),
    sa.ForeignKeyConstraint(['pinned_release_id'], ['kb_releases.id'], ),
    sa.ForeignKeyConstraint(['service_principal_id'], ['service_principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'service_principal_id', name='uq_service_grants_kb_principal')
    )
    op.create_index(op.f('ix_service_grants_kb_id'), 'service_grants', ['kb_id'], unique=False)
    op.create_index('ix_service_grants_owner_status_expires_at', 'service_grants', ['owner_wallet_address', 'grant_status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_service_grants_owner_wallet_address'), 'service_grants', ['owner_wallet_address'], unique=False)
    op.create_index(op.f('ix_service_grants_pinned_release_id'), 'service_grants', ['pinned_release_id'], unique=False)
    op.create_index(op.f('ix_service_grants_service_principal_id'), 'service_grants', ['service_principal_id'], unique=False)
    op.create_table('source_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('asset_path', sa.String(length=1024), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'asset_path', name='uq_source_assets_source_asset_path')
    )
    op.create_index('ix_source_assets_kb_availability_status', 'source_assets', ['kb_id', 'availability_status'], unique=False)
    op.create_index(op.f('ix_source_assets_kb_id'), 'source_assets', ['kb_id'], unique=False)
    op.create_index(op.f('ix_source_assets_source_id'), 'source_assets', ['source_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('index_status', sa.String(length=32), nullable=False),
    sa.Column('vector_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_embeddings_kb_id'), 'embeddings', ['kb_id'], unique=False)
    op.create_index(op.f('ix_embeddings_owner_wallet_address'), 'embeddings', ['owner_wallet_address'], unique=False)
    op.create_table('evidence_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('source_locator', sa.JSON(), nullable=False),
    sa.Column('vector_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_units_asset_id'), 'evidence_units', ['asset_id'], unique=False)
    op.create_index('ix_evidence_units_asset_id_created_at', 'evidence_units', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_evidence_units_kb_id'), 'evidence_units', ['kb_id'], unique=False)
    op.create_index('ix_evidence_units_kb_vector_status', 'evidence_units', ['kb_id', 'vector_status'], unique=False)
    op.create_table('kb_release_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_item_revision_id', sa.Integer(), nullable=False),
    sa.Column('item_version_hash', sa.String(length=128), nullable=False),
    sa.Column('content_health_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.ForeignKeyConstraint(['knowledge_item_revision_id'], ['knowledge_item_revisions.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['kb_releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'knowledge_item_id', name='uq_kb_release_items_release_item'),
    sa.UniqueConstraint('release_id', 'knowledge_item_revision_id', name='uq_kb_release_items_release_revision')
    )
    op.create_index(op.f('ix_kb_release_items_knowledge_item_id'), 'kb_release_items', ['knowledge_item_id'], unique=False)
    op.create_index(op.f('ix_kb_release_items_knowledge_item_revision_id'), 'kb_release_items', ['knowledge_item_revision_id'], unique=False)
    op.create_index(op.f('ix_kb_release_items_release_id'), 'kb_release_items', ['release_id'], unique=False)
    op.create_table('retrieval_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_wallet_address', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('service_grant_id', sa.Integer(), nullable=True),
    sa.Column('service_principal_id', sa.Integer(), nullable=True),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_mode', sa.String(length=32), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('result_summary_json', sa.JSON(), nullable=False),
    sa.Column('trace_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['owner_wallet_address'], ['wallet_users.wallet_address'], ),
    sa.ForeignKeyConstraint(['release_id'], ['kb_releases.id'], ),
    sa.ForeignKeyConstraint(['service_grant_id'], ['service_grants.id'], ),
    sa.ForeignKeyConstraint(['service_principal_id'], ['service_principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_logs_agent_run_id'), 'retrieval_logs', ['agent_run_id'], unique=False)
    op.create_index('ix_retrieval_logs_kb_created_at', 'retrieval_logs', ['kb_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_kb_id'), 'retrieval_logs', ['kb_id'], unique=False)
    op.create_index('ix_retrieval_logs_owner_created_at', 'retrieval_logs', ['owner_wallet_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_owner_wallet_address'), 'retrieval_logs', ['owner_wallet_address'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_release_id'), 'retrieval_logs', ['release_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_service_grant_id'), 'retrieval_logs', ['service_grant_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_service_principal_id'), 'retrieval_logs', ['service_principal_id'], unique=False)
    op.create_table('knowledge_item_evidence_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_item_revision_id', sa.Integer(), nullable=False),
    sa.Column('evidence_unit_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_unit_id'], ['evidence_units.id'], ),
    sa.ForeignKeyConstraint(['knowledge_item_revision_id'], ['knowledge_item_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_item_revision_id', 'evidence_unit_id', 'role', name='uq_item_revision_evidence_role')
    )
    op.create_index('ix_item_evidence_links_revision_rank', 'knowledge_item_evidence_links', ['knowledge_item_revision_id', 'rank'], unique=False)
    op.create_index(op.f('ix_knowledge_item_evidence_links_evidence_unit_id'), 'knowledge_item_evidence_links', ['evidence_unit_id'], unique=False)
    op.create_index(op.f('ix_knowledge_item_evidence_links_knowledge_item_revision_id'), 'knowledge_item_evidence_links', ['knowledge_item_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_item_evidence_links_knowledge_item_revision_id'), table_name='knowledge_item_evidence_links')
    op.drop_index(op.f('ix_knowledge_item_evidence_links_evidence_unit_id'), table_name='knowledge_item_evidence_links')
    op.drop_index('ix_item_evidence_links_revision_rank', table_name='knowledge_item_evidence_links')
    op.drop_table('knowledge_item_evidence_links')
    op.drop_index(op.f('ix_retrieval_logs_service_principal_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_service_grant_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_release_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_owner_wallet_address'), table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_owner_created_at', table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_kb_id'), table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_kb_created_at', table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_agent_run_id'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    op.drop_index(op.f('ix_kb_release_items_release_id'), table_name='kb_release_items')
    op.drop_index(op.f('ix_kb_release_items_knowledge_item_revision_id'), table_name='kb_release_items')
    op.drop_index(op.f('ix_kb_release_items_knowledge_item_id'), table_name='kb_release_items')
    op.drop_table('kb_release_items')
    op.drop_index('ix_evidence_units_kb_vector_status', table_name='evidence_units')
    op.drop_index(op.f('ix_evidence_units_kb_id'), table_name='evidence_units')
    op.drop_index('ix_evidence_units_asset_id_created_at', table_name='evidence_units')
    op.drop_index(op.f('ix_evidence_units_asset_id'), table_name='evidence_units')
    op.drop_table('evidence_units')
    op.drop_index(op.f('ix_embeddings_owner_wallet_address'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_kb_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_source_assets_source_id'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_kb_id'), table_name='source_assets')
    op.drop_index('ix_source_assets_kb_availability_status', table_name='source_assets')
    op.drop_table('source_assets')
    op.drop_index(op.f('ix_service_grants_service_principal_id'), table_name='service_grants')
    op.drop_index(op.f('ix_service_grants_pinned_release_id'), table_name='service_grants')
    op.drop_index(op.f('ix_service_grants_owner_wallet_address'), table_name='service_grants')
    op.drop_index('ix_service_grants_owner_status_expires_at', table_name='service_grants')
    op.drop_index(op.f('ix_service_grants_kb_id'), table_name='service_grants')
    op.drop_table('service_grants')
    op.drop_index(op.f('ix_knowledge_item_revisions_knowledge_item_id'), table_name='knowledge_item_revisions')
    op.drop_index('ix_knowledge_item_revisions_item_review_visibility', table_name='knowledge_item_revisions')
    op.drop_table('knowledge_item_revisions')
    op.drop_index(op.f('ix_import_task_items_task_id'), table_name='import_task_items')
    op.drop_table('import_task_items')
    op.drop_index(op.f('ix_chunks_owner_wallet_address'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_kb_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_agent_run_steps_run_id'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index(op.f('ix_agent_run_inputs_run_id'), table_name='agent_run_inputs')
    op.drop_table('agent_run_inputs')
    op.drop_index(op.f('ix_agent_run_events_run_id'), table_name='agent_run_events')
    op.drop_table('agent_run_events')
    op.drop_index(op.f('ix_agent_run_artifacts_run_id'), table_name='agent_run_artifacts')
    op.drop_table('agent_run_artifacts')
    op.drop_index('ix_sources_kb_sync_status', table_name='sources')
    op.drop_index(op.f('ix_sources_kb_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_source_bindings_kb_id'), table_name='source_bindings')
    op.drop_index(op.f('ix_source_bindings_credential_id'), table_name='source_bindings')
    op.drop_table('source_bindings')
    op.drop_index(op.f('ix_memory_ingestion_events_session_id'), table_name='memory_ingestion_events')
    op.drop_index(op.f('ix_memory_ingestion_events_owner_wallet_address'), table_name='memory_ingestion_events')
    op.drop_index(op.f('ix_memory_ingestion_events_kb_id'), table_name='memory_ingestion_events')
    op.drop_table('memory_ingestion_events')
    op.drop_index(op.f('ix_memories_long_term_owner_wallet_address'), table_name='memories_long_term')
    op.drop_index(op.f('ix_memories_long_term_kb_id'), table_name='memories_long_term')
    op.drop_table('memories_long_term')
    op.drop_index('ix_knowledge_items_kb_lifecycle_status', table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_kb_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_current_revision_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index('ix_knowledge_item_candidates_kb_review_status', table_name='knowledge_item_candidates')
    op.drop_index(op.f('ix_knowledge_item_candidates_kb_id'), table_name='knowledge_item_candidates')
    op.drop_table('knowledge_item_candidates')
    op.drop_index(op.f('ix_kb_releases_supersedes_release_id'), table_name='kb_releases')
    op.drop_index('ix_kb_releases_kb_status_published_at', table_name='kb_releases')
    op.drop_index(op.f('ix_kb_releases_kb_id'), table_name='kb_releases')
    op.drop_table('kb_releases')
    op.drop_index('ix_import_tasks_status_created_at', table_name='import_tasks')
    op.drop_index(op.f('ix_import_tasks_owner_wallet_address'), table_name='import_tasks')
    op.drop_index('ix_import_tasks_owner_status_created_at', table_name='import_tasks')
    op.drop_index(op.f('ix_import_tasks_kb_id'), table_name='import_tasks')
    op.drop_table('import_tasks')
    op.drop_index(op.f('ix_documents_owner_wallet_address'), table_name='documents')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_agent_runs_service_principal_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_principal_created_at', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_owner_wallet_address'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_owner_created_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_service_principals_owner_wallet_address'), table_name='service_principals')
    op.drop_index('ix_service_principals_owner_status', table_name='service_principals')
    op.drop_table('service_principals')
    op.drop_index(op.f('ix_passport_subjects_wallet_address'), table_name='passport_subjects')
    op.drop_table('passport_subjects')
    op.drop_index(op.f('ix_knowledge_bases_owner_wallet_address'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_table('worker_status')
    op.drop_index(op.f('ix_warehouse_access_credentials_owner_wallet_address'), table_name='warehouse_access_credentials')
    op.drop_table('warehouse_access_credentials')
    op.drop_table('wallet_users')
    op.drop_index(op.f('ix_upload_records_owner_wallet_address'), table_name='upload_records')
    op.drop_table('upload_records')
    op.drop_index(op.f('ix_passport_login_sessions_wallet_address'), table_name='passport_login_sessions')
    op.drop_index(op.f('ix_passport_login_sessions_subject_id'), table_name='passport_login_sessions')
    op.drop_table('passport_login_sessions')
    op.drop_index(op.f('ix_memories_short_term_session_id'), table_name='memories_short_term')
    op.drop_index(op.f('ix_memories_short_term_owner_wallet_address'), table_name='memories_short_term')
    op.drop_table('memories_short_term')
    op.drop_index(op.f('ix_auth_challenges_wallet_address'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    # ### end Alembic commands ###
