import { useEffect, useState } from "react";
import { sourcesApi, type Evidence, type Source } from "./api";
import { request } from "../../api/client";

export function SourcesWorkspace({ kbId }: { kbId: number }) {
  const [sources, setSources] = useState<Source[]>([]); const [name, setName] = useState(""); const [path, setPath] = useState(""); const [type, setType] = useState("local_file");
  const [evidence, setEvidence] = useState<Evidence[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { sourcesApi.listSources(kbId).then(setSources); }, [kbId]);
  async function createSource() { if (!kbId || !path.trim()) return; await sourcesApi.createSource(kbId, type, path.trim()); setPath(""); setSources(await sourcesApi.listSources(kbId)); }
  async function run(source: Source, action: "scan" | "build" | "evidence" | "candidates") { setMessage(""); if (action === "scan") await sourcesApi.scan(kbId, source.id); if (action === "build") await sourcesApi.buildEvidence(kbId, source.id); if (action === "evidence") setEvidence(await sourcesApi.evidence(kbId, source.id)); if (action === "candidates") await request(`/kbs/${kbId}/sources/${source.id}/generate-candidates`, { method: "POST" }); setSources(await sourcesApi.listSources(kbId)); setMessage(action === "scan" ? "来源扫描完成。" : action === "build" ? "Evidence 构建完成。" : action === "candidates" ? "候选知识已生成，请在下方审核。" : ""); }
  return <><section className="panel"><h2>添加来源</h2><div className="form-row"><select value={type} onChange={(e) => setType(e.target.value)}><option value="local_file">本地目录</option><option value="github_repository">GitHub 仓库</option></select><input value={path} onChange={(e) => setPath(e.target.value)} placeholder={type === "local_file" ? "例如 docs" : "owner/repository@main:docs"}/><button onClick={createSource}>添加</button></div></section><section className="panel"><h2>已接入来源</h2>{sources.map((source) => <div className="source-row" key={source.id}><div><strong>{source.source_path}</strong><span>{source.source_type} · {source.sync_status}</span></div><div><button onClick={() => run(source, "scan")}>扫描</button><button onClick={() => run(source, "build")}>构建 Evidence</button><button onClick={() => run(source, "candidates")}>生成候选</button><button onClick={() => run(source, "evidence")}>查看</button></div></div>)}{!sources.length && <p className="muted">尚未添加来源。</p>}</section>{message && <p className="notice">{message}</p>}{evidence.length > 0 && <section className="panel"><h2>Evidence</h2>{evidence.map((item) => <article className="evidence" key={item.id}><strong>#{item.id}</strong><p>{item.text}</p></article>)}</section>}</>;
}
